# Generated by Django 5.2.1 on 2025-06-30 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_comment_user_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text_com',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='news_choice_article',
            new_name='post_type',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text_n_ar',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='heading',
            new_name='title',
        ),
    ]
